In [1]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# 2. Create a vector with values ranging from 10 to 49.

arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

arr = np.arange(9).reshape(3,3)
print (arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


In [5]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

arr = np.random.random((10,10))
arrmin = arr.min()
arrmax = arr.max()
print(arrmin, arrmax)

0.00011147502686326138 0.9805663121128284


In [6]:
# 6. Create a random vector of size 30 and find the mean value.

arr = np.random.random(10)
m = arr.mean()
print (m)

0.6857340388390207
